services:
  mongo:
    image: mongo:latest
    container_name: qtsbook-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    env_file: .env
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo-express:
    image: mongo-express:latest
    container_name: qtsbook-mongo-express
    ports:
      - "8081:8081"
    env_file: .env
    environment:
      ME_CONFIG_MONGODB_SERVER: ${ME_CONFIG_MONGODB_SERVER:-mongo}
    depends_on:
      mongo:
        condition: service_healthy

  app:
    build:
      context: .
    container_name: qtsbook-app
    env_file: .env
    volumes:
      - ./:/app
    working_dir: /app
    depends_on:
      mongo:
        condition: service_healthy
    ports:
      - "8000:8000"
    command: bash -lc "uvicorn app.api.main:app --host 0.0.0.0 --port 8000"

  scheduler:
    build:
      context: .
    container_name: qtsbook-scheduler
    env_file: .env
    volumes:
      - ./:/app
    working_dir: /app
    depends_on:
      mongo:
        condition: service_healthy
    command: bash -lc "python -m scheduler.schedule_daily"

volumes:
  mongo_data:
